* This do file run the regression specification in Yawen's "Does Trade Liberalization Induce Occupational Movement?"
* The regressions in this file are run at region-skill-gender level
* Agricultural occupations and production are included

* input data are generated by Bartik_15Nov22.do and delta_15Nov22.do

* Last updated: Oct 28th,2015

set more off
cd "C:\PhD Study\Year 3\Projects\Job Porlarization\Arranged Files"
clear

use "data\temp\HH9006_15Aug30_cln.dta", clear /* generaged by Bartik_15Oct17.do */
keep if year==1990|year==1996|year==1997|year==2002|year==2006

ren abstract cognitive
* define new occupation group: agriculture
gen agct = 0
replace agct = 1 if isco68_2d>=60 & isco68_2d<=64
replace LFSind = 10 if LFSind >=11 & LFSind<=18 /* agricultural industry */
*drop if agct==1 & LFSind != 10 /* agricultural occupations are only used in agricultral industries */
*replace agct = 1 if LFSind==10 /* workers in agricultral industries are all in agricultural occupations */
*replace LFSind = 10 & agct==1 /* agricultural occupations are only used in agricultral industries */

replace cognitive = 0 if agct==1
replace routine = 0 if agct==1
replace manual = 0 if agct==1

gen kabkode = prov*100+kabu
replace kabkode = kabu if kabu>99

* use the region correspondence table to get consistent region code
sort year
levelsof year, local(yr)
gen code1990_temp=.
gen name1990_temp=.
tostring(name1990), replace force
foreach val in `yr'{
gen code`val' = kabkode if year==`val'
merge m:1 code`val' using "data\temp\code90`val'.dta" /* these files are generated at the begining of this file */
drop if _merge!=3 & year==`val'
replace code1990_temp = code1990 if year==`val'
replace name1990_temp = name1990 if year==`val'
drop code1990 name1990 code`val' name`val' _merge
}
ren code1990_temp code1990 /* the 1990 name and code are used for all years */
ren name1990_temp name1990 /* the 1990 name and code are used for all years */
drop if kabkode==.

gen l = 1

gen dmale = .
replace dmale = 1 if gender==1
replace dmale = 0 if gender==2

gen grp1 = dmale*skill
gen grp2 = dmale*(1-skill)
gen grp3 = (1-dmale)*skill
gen grp4 = (1-dmale)*(1-skill)

egen grp = group(grp4 grp3 grp2 grp1)

drop if agct==1
collapse (sum) cognitive routine manual agct l skill dmale grp1-grp4 (mean) lnRTI r_cog r_man offshor nr* expc yrschool (rawsum) wtper [aweight=wtper], by(year code1990 grp)

save "data\temp\HHNov22_temp.dta",replace

use "data\temp\HHNov22_temp.dta",clear
keep if year==1990|year==1996|year==1997|year==2002|year==2006

* generate region-group variables
ren l L_kabgrp

foreach item in cognitive routine manual agct{
gen `item'_shr_grp = `item'/L_kabgrp  /* occupation shares within groups */
gen ln`item'_shr_grp = ln(`item'_shr_grp)
}

* generate regional variables

bys year code1990: egen L_kab = sum(L_kabgrp)
foreach item in cognitive routine manual agct{
bys year code1990: egen `item'_kab=sum(`item')
gen `item'_shr_kab = `item'_kab/L_kab
}
foreach num of numlist 1/4{
bys year code1990: egen grp`num'_kab = sum(grp`num')
gen lngrp`num'_kab = ln(grp`num'_kab)
*gen grp`num'_shr = grp`num'_kab/L_kab
}

* generate changes
gen id = code1990*10+grp
xtset id year

gen Y1 = routine_shr_grp/cognitive_shr_grp
gen Y2 = routine_shr_grp/manual_shr_grp

foreach Y in Y1 Y2{
gen ln`Y' = ln(`Y')
gen dln`Y' = ln`Y'-L6.ln`Y' if year==1996
replace dln`Y' = ln`Y'-L4.ln`Y' if year==2006
}

foreach num of numlist 1/4{
gen dlngrp`num'_kab = lngrp`num'_kab-L6.lngrp`num'_kab if year==1996
replace dlngrp`num'_kab = lngrp`num'_kab-L4.lngrp`num'_kab if year==2006
}

foreach item in cognitive routine manual agct{
gen L`item'_shr_kab = L6.`item'_shr_kab if year==1996
replace L`item'_shr_kab = L4.`item'_shr_kab if year==2006
}

gen prov1990 = int(code1990/100)
keep if year==1996|year==2006
merge m:1 code1990 year using "data\output\WITS_kabyr9006bg_15Nov22.dta" /* generated by Bartik_15Oct26.do */
keep if _merge==3
drop _merge
save "data\temp\regression_Nov22.dta",replace


********************************************************************
use "data\temp\regression_Oct28.dta",clear
keep year code1990 grp
merge 1:1 year code1990 grp using "data\temp\regression_Nov22.dta"
keep if _merge==3 /* use the same sample */
drop _merge

foreach task in c r m a{
ren delta_`task'_kab delta_`task'
replace delta_`task'=delta_`task'*100
}

foreach task in c r m a{
gen delta_`task'XdlnnxWLD_`task'_kab = delta_`task'*dlnnxWLD_`task'_kab
gen delta_fullXdlnnxWLD_`task'_kab = delta_c*delta_r*delta_m*dlnnxWLD_`task'_kab
* additional interaction (with the initial shares of other tasks):
gen LmanualXdelta_`task'XdlnnxWLD_`task'_kab = Lmanual_shr_kab*delta_`task'XdlnnxWLD_`task'_kab
gen LcognXdelta_`task'XdlnnxWLD_`task'_kab = Lcognitive_shr_kab*delta_`task'XdlnnxWLD_`task'_kab
gen LagctXdelta_`task'XdlnnxWLD_`task'_kab = Lagct_shr_kab*delta_`task'XdlnnxWLD_`task'_kab
}

replace delta_fullXdlnnxWLD_a_kab = delta_c*delta_r*delta_m*dlnnxWLD_a_kab 



foreach item in c r m{
foreach num of numlist 1/4{
gen delta_`item'Xdlngp`num' = delta_`item'*dlngrp`num'
}
}


*foreach num of numlist 1/4{
*gen delta_FullXdlngp`num' = delta_c*delta_r*delta_c*dlngrp`num'
*}



foreach num of numlist 1/4{
gen LmanualXdlngp`num' = Lmanual_shr_kab*dlngrp`num'
gen LcognitiveXdlngp`num' = Lcognitive_shr_kab*dlngrp`num'
gen LagctXdlngp`num' = Lagct_shr_kab*dlngrp`num'
}

set more off

****1. Short periods
global delta delta_c delta_r delta_m delta_a

* regressor set 1 (change in log)
global dlnx dlngrp*
global deltaXdlnx delta_*dlngp*
global dlnnxWLD dlnnxWLD_c_kab dlnnxWLD_r_kab dlnnxWLD_m_kab 
global deltaXdlnnxWLD delta_cXdlnnxWLD_c_kab delta_rXdlnnxWLD_r_kab delta_mXdlnnxWLD_m_kab
global deltaXdlnnxWLD_full delta_fullXdlnnxWLD_c_kab delta_fullXdlnnxWLD_r_kab delta_fullXdlnnxWLD_m_kab

* pick the regressor set
global Y1 dlnY1 
global Y2 dlnY2 
 
global X1 $dlnnxWLD
global X1_A dlnnxWLD_a_kab
global X2 $deltaXdlnnxWLD
global X2_A dlnnxWLD_a_kab
global X3 $deltaXdlnnxWLD_full
global X3_A delta_fullXdlnnxWLD_a_kab 

global X4 $dlnx 
global X5 $deltaXdlnx 
global X6 Lmanual_shr_kab
global X7 Lcognitive_shr_kab
global X8 Lagct_shr_kab

duplicates tag code1990 grp,gen(dup)
keep if dup==1


* 1. OLS
levelsof year, local(yr)

* 1.1 log changes
	
foreach pd in `yr'{

reg $Y1 $X2 $X2_A $X3 $X3_A $X4 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Nov22_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) replace

reg $Y1 $X2 $X2_A $X3 $X3_A $X4 $X5 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Nov22_15\\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

reg $Y1 $X2 $X2_A $X3 $X3_A $X4 $X5 $X6 $X8 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Nov22_15\\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

reg $Y2 $X2 $X2_A $X3 $X3_A $X4 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Nov22_15\\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append

reg $Y2 $X2 $X2_A $X3 $X3_A $X4 $X5 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Nov22_15\\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

reg $Y2 $X2 $X2_A $X3 $X3_A $X4 $X5 $X7 $X8 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Nov22_15\\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append
}


* 2. IV

* 2.1 IV estimations (log changes)

* use distance to port, distance to airport, port dummies and related interactions to instrument the three shocks
merge m:1 code1990 using "data\output\distances_code1990.do"
drop if _merge==2

foreach task in c r m a{
gen delta_`task'Xdist_port = delta_`task'*cdist_port
gen delta_`task'Xdist_airport = delta_`task'*cdist_airport
gen delta_`task'Xdport = delta_`task'*dport
gen delta_`task'Xdaport = delta_`task'*daport
gen delta_`task'Xdlntariff_`task'_kab = delta_`task'*dlntariff_`task'_kab
}
foreach task in c r m{
gen delta_fullXdlntariff_`task'_kab = delta_c*delta_r*delta_m*dlntariff_`task'_kab
}
gen delta_fullXdlntariff_a_kab = delta_c*delta_r*delta_m*dlntariff_a_kab /* Derived from the model, the effect of Y*_A does NOT depend on delta_A ! */

*IV set 

global IV1 delta_cXdlntariff_c_kab delta_rXdlntariff_r_kab delta_mXdlntariff_m_kab
global IV2 delta_fullXdlntariff_c_kab delta_fullXdlntariff_r_kab delta_fullXdlntariff_m_kab
global IV3 cdist_port cdist_airport dport daport

set more off

* (include distances)
levelsof year, local(yr)
foreach pd in `yr'{

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X2_A $X3_A $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) replace

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X2_A $X3_A $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X2_A $X3_A $X4 $X5 $X6 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X2_A $X3_A $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X2_A $X3_A $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X2_A $X3_A $X4 $X5 $X7 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X2_A $X3 $X3_A $X4) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append
}

stop

*************************
**************************************************************************************************************************************
* The following are the IV regressions without agriculture sector (just a note, run the regreesion using "regressionsYawen_15Oct28.do"
**************************************************************************************************************************************
levelsof year, local(yr)
foreach pd in `yr'{

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) replace

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 $X6 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 $X7 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Nov22_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

}

stop
**********************************
** selected 1st stage regression
collapse (mean) dlnnxWLD_*_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport, by(year code1990)
gen prov = int(code1990/100)

reg dlnnxWLD_c_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==1996
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport ) addtext(Prov. FE, Yes, Period, 1990-1996) replace

reg dlnnxWLD_r_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port  cdist_airport if year==1996
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 1990-1996) append

reg dlnnxWLD_m_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==1996
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 1990-1996) append

reg dlnnxWLD_a_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==1996
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 1990-1996) append


reg dlnnxWLD_c_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==2006
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 2002-2006) append

reg dlnnxWLD_r_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==2006
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 2002-2006) append

reg dlnnxWLD_m_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==2006
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 2002-2006) append

reg dlnnxWLD_a_kab dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport if year==2006
outreg2 using "results\Nov22_15\table1stage_region",se coefastr bdec(3) tex nolabel keep(dlntariff_c_kab dlntariff_r_kab dlntariff_m_kab dlntariff_a_kab cdist_port cdist_airport) addtext(Prov. FE, Yes, Period, 2002-2006) append























