* This do file run the regression specification in Yawen's "Does Trade Liberalization Induce Occupational Movement?"
* Deifferent from previous versions, the regressions in this file are run at region-skill-gender level

* input data are generated by Bartik_16Oct26.do and delta_15Oct26.do

* Last updated: Oct 28th,2015



set more off
cd "C:\PhD Study\Year 3\Projects\Job Porlarization\Arranged Files"
clear



foreach num of numlist 1990 1994/2006{
clear
use "data\output\kabkode_matched9305.dta"
keep code1990 name1990 code`num' name`num'
duplicates drop code`num',force
save "data\temp\code90`num'",replace
}

use "data\temp\HH9006_15Aug30_cln.dta", clear /* generaged by Bartik_15Oct17.do */
*(Farmers are included when constructing Bartik shocks, but they are excluded from regressions as they have low mobility across occupations)

*** drop agriculture workers
* drop farming supervisors
drop if isco68_2d==60
* drop farmers
drop if isco68_2d==61
* drop other agriculture workers
drop if isco68_2d>=62 & isco68_2d<=64


gen kabkode = prov*100+kabu
replace kabkode = kabu if kabu>99
* use the region correspondence table to get consistent region code

sort year
levelsof year, local(yr)
gen code1990_temp=.
gen name1990_temp=.
tostring(name1990), replace force
foreach val in `yr'{
gen code`val' = kabkode if year==`val'
merge m:1 code`val' using "data\temp\code90`val'.dta" /* these files are generated at the begining of this file */
drop if _merge!=3 & year==`val'
replace code1990_temp = code1990 if year==`val'
replace name1990_temp = name1990 if year==`val'
drop code1990 name1990 code`val' name`val' _merge
}
ren code1990_temp code1990 /* the 1990 name and code are used for all years */
ren name1990_temp name1990 /* the 1990 name and code are used for all years */
drop if kabkode==.

gen l = 1

gen dmale = .
replace dmale = 1 if gender==1
replace dmale = 0 if gender==2

gen grp1 = dmale*skill
gen grp2 = dmale*(1-skill)
gen grp3 = (1-dmale)*skill
gen grp4 = (1-dmale)*(1-skill)

egen grp = group(grp4 grp3 grp2 grp1)

collapse (sum) abstract routine manual l skill dmale grp1-grp4 (mean) lnRTI r_cog r_man offshor nr* expc yrschool (rawsum) wtper [aweight=wtper], by(year code1990 grp)

save "data\temp\HHOct28_temp.dta",replace

use "data\temp\HHOct28_temp.dta",clear
keep if year==1990|year==1996|year==1997|year==2002|year==2006

* generate region-group variables
ren l L_kabgrp

foreach item in abstract routine manual{
gen `item'_shr_grp = `item'/L_kabgrp  /* occupation shares within groups */
gen ln`item'_shr_grp = ln(`item'_shr_grp)
}

* generate regional variables

bys year code1990: egen L_kab = sum(L_kabgrp)
foreach item in abstract routine manual{
bys year code1990: egen `item'_kab=sum(`item')
gen `item'_shr_kab = `item'_kab/L_kab
}
foreach num of numlist 1/4{
bys year code1990: egen grp`num'_kab = sum(grp`num')
gen lngrp`num'_kab = ln(grp`num'_kab)
*gen grp`num'_shr = grp`num'_kab/L_kab
}

* generate changes
gen id = code1990*10+grp
xtset id year

gen Y1 = routine_shr_grp/abstract_shr_grp
gen Y2 = routine_shr_grp/manual_shr_grp

foreach Y in Y1 Y2{
gen ln`Y' = ln(`Y')
gen dln`Y' = ln`Y'-L6.ln`Y' if year==1996
replace dln`Y' = ln`Y'-L4.ln`Y' if year==2006
gen L`Y' = L6.`Y' if year==1996
replace L`Y' = L4.`Y' if year==2006
}

gen LL_kabgrp = L6.L_kabgrp if year==1996
replace LL_kabgrp = L4.L_kabgrp if year==2006

foreach num of numlist 1/4{
gen dlngrp`num'_kab = lngrp`num'_kab-L6.lngrp`num'_kab if year==1996
replace dlngrp`num'_kab = lngrp`num'_kab-L4.lngrp`num'_kab if year==2006
}

foreach item in abstract routine manual{
gen L`item'_shr_kab = L6.`item'_shr_kab if year==1996
replace L`item'_shr_kab = L4.`item'_shr_kab if year==2006
}

gen prov1990 = int(code1990/100)
keep if year==1996|year==2006
merge m:1 code1990 year using "data\output\WITS_kabyr9006bg_15Oct26.dta" /* generated by Bartik_15Oct26.do */
keep if _merge==3
drop _merge
save "data\temp\regression_Oct28.dta",replace



********************************************************************
use "data\temp\regression_Oct28.dta",clear
*merge m:1 year code1990 using "data\output\kabexp_shr_Oct26.dta" /* generated by delta_15Oct26.do */ <---- this part is down in Bartik_15Oct17
*keep if _merge==3
*drop _merge

foreach task in a r m{
ren delta_`task'_kab delta_`task'
replace delta_`task'=delta_`task'*100
}

foreach task in a r m{
gen delta_`task'XdlnnxWLD_`task'_kab = delta_`task'*dlnnxWLD_`task'_kab
gen delta_fullXdlnnxWLD_`task'_kab = delta_a*delta_r*delta_m*dlnnxWLD_`task'_kab
gen LmanualXdelta_`task'XdlnnxWLD_`task'_kab = Lmanual_shr_kab*delta_`task'XdlnnxWLD_`task'_kab
gen LabstractXdelta_`task'XdlnnxWLD_`task'_kab = Labstract_shr_kab*delta_`task'XdlnnxWLD_`task'_kab
}


foreach item in a r m{
foreach num of numlist 1/4{
gen delta_`item'Xdlngp`num' = delta_`item'*dlngrp`num'
}
}

foreach num of numlist 1/4{
gen LmanualXdlngp`num' = Lmanual_shr_kab*dlngrp`num'
gen LabstractXdlngp`num' = Labstract_shr_kab*dlngrp`num'
}

set more off
****1. Short periods
global delta delta_a delta_r delta_m

* regressor set 1 (change in log)
global dlnx dlngrp*
global deltaXdlnx delta_*dlngp*
global dlnnxWLD dlnnxWLD_a_kab dlnnxWLD_r_kab dlnnxWLD_m_kab
global deltaXdlnnxWLD delta_aXdlnnxWLD_a_kab delta_rXdlnnxWLD_r_kab delta_mXdlnnxWLD_m_kab
global deltaXdlnnxWLD_full delta_fullXdlnnxWLD_a_kab delta_fullXdlnnxWLD_r_kab delta_fullXdlnnxWLD_m_kab 

* pick the regressor set
global Y1 dlnY1 /* options: dlnY1 pctdY1 */
global Y2 dlnY2 /* options: dlnY2 pctdY2 */
 
global X1 $dlnnxWLD /* options: $dlnYwtnxWLD $pctdYwtnxWLD */
global X2 $deltaXdlnnxWLD /* options: $deltaXdlnYwtnxWLD $deltaXpctdYwtnxWLD */
global cX2 c.delta_aXdlnnxWLD_a_kab c.delta_rXdlnnxWLD_r_kab c.delta_mXdlnnxWLD_m_kab
global X3 $deltaXdlnnxWLD_full /* options: $deltaXdlnYwtnxWLD_full $$deltaXpctdYwtnxWLD_full */

global X4 $dlnx /* options: $dlnx $pctdx */
global X5 $deltaXdlnx /* options: $deltaXdlnx $deltaXpctdx */
global X6 Lmanual_shr_kab
global X7 Labstract_shr_kab
global X8 LmanualXdelta_*XdlnnxWLD_*_kab
global X9 LabstractXdelta_*XdlnnxWLD_*_kab
duplicates tag code1990 grp,gen(dup)
keep if dup==1

* 1. OLS
levelsof year, local(yr)

* 1.1 log changes
	
foreach pd in `yr'{

*reg $Y1 $X1 $X4 i.prov if year==`pd',r
*outreg2 using "results\Oct25_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X1 $X4 ) addtext(Prov. FE, YES, Period, `pd', dlnxXdelta, No) replace

*reg $Y1 $X2 $X4 i.prov i.grp if year==`pd',r
*outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X4) addtext(Prov. FE, Yes, Period, `pd', dlnxXdelta, No) replace

reg $Y1 $X2 $X3 $X4 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) replace

reg $Y1 $X2 $X3 $X4 $X5 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

reg $Y1 $X2 $X3 $X4 $X5 $X6 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append


*reg $Y2 $X1 $X4 i.prov if year==`pd',r
*outreg2 using "results\Oct25_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X1 $X4 ) addtext(Prov. FE, YES, Period, `pd', dlnxXdelta, No) append

*reg $Y2 $X2 $X4 i.prov i.grp if year==`pd',r
*outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X4) addtext(Prov. FE, Yes, Period, `pd', dlnxXdelta, No) append

reg $Y2 $X2 $X3 $X4 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append

reg $Y2 $X2 $X3 $X4 $X5 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

reg $Y2 $X2 $X3 $X4 $X5 $X7 i.prov i.grp if year==`pd',cluster(code1990)
outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append
}

* 2. IV

* 2.1 IV estimations (log changes)

* use distance to port, distance to airport, port dummies and related interactions to instrument the three shocks
merge m:1 code1990 using "data\output\distances_code1990.do"
drop if _merge==2

foreach task in a r m{
gen delta_`task'Xdist_port = delta_`task'*cdist_port
gen delta_`task'Xdist_airport = delta_`task'*cdist_airport
gen delta_`task'Xdport = delta_`task'*dport
gen delta_`task'Xdaport = delta_`task'*daport

gen delta_`task'Xdlntariff_`task'_kab = delta_`task'*dlntariff_`task'_kab
gen delta_fullXdlntariff_`task'_kab = delta_a*delta_r*delta_m*dlntariff_`task'_kab
}

*IV set 

global IV1 delta_aXdlntariff_a_kab delta_rXdlntariff_r_kab delta_mXdlntariff_m_kab
global IV2 delta_fullXdlntariff_a_kab delta_fullXdlntariff_r_kab delta_fullXdlntariff_m_kab
global IV3 cdist_port cdist_airport dport daport


set more off

* (exclude distances)
levelsof year, local(yr)
foreach pd in `yr'{
*ivregress 2sls $Y1 ($X2 = $IV1) $X4 i.prov i.grp if year==`pd', cluster(code1990)
*outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X4) addtext(Prov. FE, Yes, Period, `pd', IV, IV1,dlnxXdelta, No) replace

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2) $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) replace

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2) $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2) $X4 $X5 $X6 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

*ivregress 2sls $Y2 ($X2 = $IV1) $X4 i.prov i.grp if year==`pd', cluster(code1990)
*outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X4) addtext(Prov. FE, Yes, Period, `pd', IV, IV1,dlnxXdelta, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2) $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes,  Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2) $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2) $X4 $X5 $X7 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table1IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes,  Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append
}


* (include distances)
levelsof year, local(yr)
foreach pd in `yr'{

*ivregress 2sls $Y1 ($X2 = $IV1 $IV3) $X4 i.prov i.grp if year==`pd', cluster(code1990)
*outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X4) addtext(Prov. FE, Yes, Period, `pd', IV, IV1+IV3,dlnxXdelta, No) replace

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) replace

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y1 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 $X6 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

*ivregress 2sls $Y2 ($X2 = $IV1 $IV3) $X4 i.prov i.grp if year==`pd', cluster(code1990)
*outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X4) addtext(Prov. FE, Yes, Period, `pd', IV, IV1+IV3,dlnxXdelta, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, No) append

ivregress 2sls $Y2 ($X2 $X3 = $IV1 $IV2 $IV3) $X4 $X5 $X7 i.prov i.grp if year==`pd', cluster(code1990)
outreg2 using "results\Oct28_15\table2IV`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, Yes, 3rd Task Share, Yes) append

}
stop


** effect of trade by group
*reg $Y1 $X2 $X3 $X4 i.grp#($cX2) $X5 i.prov if year==`pd',cluster(code1990)
*outreg2 using "results\Oct28_15\table1`pd'_region",se coefastr bdec(3) tex nolabel keep($X2 $X3 $X4 i.grp#$cX2) addtext(Prov. FE, Yes, Group FE, Yes, dlnxXdelta, No, 3rd Task Share, No) append




** selected 1st stage regression
collapse (mean) dlnnxWLD_*_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport, by(year code1990)
gen prov = int(code1990/100)

* 1 IV for each endogenous variable

* small instrument set
reg dlnnxWLD_a_kab dlntariff_a_kab   if year==1996,robust
outreg2 using "results\Oct28_15\table1stage0_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab) addtext(Period, 1990-1996) replace

reg dlnnxWLD_r_kab dlntariff_r_kab   if year==1996,robust
outreg2 using "results\Oct28_15\table1stage0_region",se coefastr bdec(3) tex nolabel keep(dlntariff_r_kab ) addtext(Period, 1990-1996) append

reg dlnnxWLD_m_kab dlntariff_m_kab  if year==1996,robust
outreg2 using "results\Oct28_15\table1stage0_region",se coefastr bdec(3) tex nolabel keep(dlntariff_m_kab ) addtext(Period, 1990-1996) append

reg dlnnxWLD_a_kab dlntariff_a_kab if year==2006,robust
outreg2 using "results\Oct28_15\table1stage0_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab) addtext(Period, 2002-2006) append

reg dlnnxWLD_r_kab dlntariff_r_kab if year==2006,robust
outreg2 using "results\Oct28_15\table1stage0_region",se coefastr bdec(3) tex nolabel keep(dlntariff_r_kab) addtext(Period, 2002-2006) append

reg dlnnxWLD_m_kab dlntariff_m_kab  if year==2006,robust
outreg2 using "results\Oct28_15\table1stage0_region",se coefastr bdec(3) tex nolabel keep(dlntariff_m_kab ) addtext(Period, 2002-2006) append



* small instrument set
reg dlnnxWLD_a_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  if year==1996,robust
outreg2 using "results\Oct28_15\table1stage1_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab ) addtext(Period, 1990-1996) replace

reg dlnnxWLD_r_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  if year==1996,robust
outreg2 using "results\Oct28_15\table1stage1_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab ) addtext(Period, 1990-1996) append

reg dlnnxWLD_m_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  if year==1996,robust
outreg2 using "results\Oct28_15\table1stage1_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab ) addtext(Period, 1990-1996) append

reg dlnnxWLD_a_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  if year==2006,robust
outreg2 using "results\Oct28_15\table1stage1_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab ) addtext(Period, 2002-2006) append

reg dlnnxWLD_r_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  if year==2006,robust
outreg2 using "results\Oct28_15\table1stage1_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab ) addtext(Period, 2002-2006) append

reg dlnnxWLD_m_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  if year==2006,robust
outreg2 using "results\Oct28_15\table1stage1_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab ) addtext(Period, 2002-2006) append


* large instrument set
reg dlnnxWLD_a_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport if year==1996,robust
outreg2 using "results\Oct28_15\table1stage2_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport ) addtext(Period, 1990-1996) replace

reg dlnnxWLD_r_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport if year==1996,robust
outreg2 using "results\Oct28_15\table1stage2_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 1990-1996) append

reg dlnnxWLD_m_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport if year==1996,robust
outreg2 using "results\Oct28_15\table1stage2_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 1990-1996) append

reg dlnnxWLD_a_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport if year==2006,robust
outreg2 using "results\Oct28_15\table1stage2_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 2002-2006) append

reg dlnnxWLD_r_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab  cdist_port cdist_airport if year==2006,robust
outreg2 using "results\Oct28_15\table1stage2_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 2002-2006) append

reg dlnnxWLD_m_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport if year==2006,robust
outreg2 using "results\Oct28_15\table1stage2_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 2002-2006) append


* all instruments and exogenous variables
reg dlnnxWLD_a_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport $X4 i.prov i.grp if year==1996,robust
outreg2 using "results\Oct28_15\table1stage3_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport ) addtext(Period, 1990-1996) replace

reg dlnnxWLD_r_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport $X4 i.prov i.grp if year==1996,robust
outreg2 using "results\Oct28_15\table1stage3_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 1990-1996) append

reg dlnnxWLD_m_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport $X4 i.prov i.grp if year==1996,robust
outreg2 using "results\Oct28_15\table1stage3_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 1990-1996) append

reg dlnnxWLD_a_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport $X4 i.prov i.grp if year==2006,robust
outreg2 using "results\Oct28_15\table1stage3_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 2002-2006) append

reg dlnnxWLD_r_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport $X4 i.prov i.grp if year==2006,robust
outreg2 using "results\Oct28_15\table1stage3_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 2002-2006) append

reg dlnnxWLD_m_kab dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport $X4 i.prov i.grp if year==2006,robust
outreg2 using "results\Oct28_15\table1stage3_region",se coefastr bdec(3) tex nolabel keep(dlntariff_a_kab dlntariff_r_kab dlntariff_m_kab cdist_port cdist_airport) addtext(Period, 2002-2006) append



